---
- name: sample book
  hosts: webservers
  remote_user: root
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: run httpd
      service:
        name: httpd
        state: started
    - name: create content
      copy: 
        content: "Congrats on ansible ish"
        dest: /var/www/html/index.html
