---
- name: installing stuff
  hosts: webservers
  remote_user: root
  become: true
  tasks:
   - name: Install softwares
     yum:
       name: git,chromedriver
       state: present
       update_cache: yes
   - name: Install Google Chrome repo
     get_url: 
       url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
       dest: /home/loadbalancer

